### ISSUE TITLE
Collapsable Main Menu

### ISSUE THREAD

**Issue by alirizakeles** [zetaops/ulakbus-ui#10]
1024 cozunurlukler icin otomatik, daha yuksek cozunurluklerde de istege bagli collapsable menu yapilmasi

**Comment by ghost** [comment]
commit: https://github.com/zetaops/ulakbus-ui/commit/59805ca7b44257942489bc04e0527bc60d882145 ile yapildi

**Comment by ghost** [comment]
https://github.com/zetaops/ulakbus-ui/commit/718a96bba6d3c0c3792644f5f270d52337aeb6d7 ile duzenlendi
