### ISSUE TITLE
Dashborad duzenlemeleri

### ISSUE THREAD

**Issue by alirizakeles** [zetaops/ulakbus-ui#11]
- task
- notification
- report
- messages

alanlarinin gorunur hale getirilmesi

**Comment by ghost** [comment]
@erkanogum slack uzerinden bir sablon paylastim. ona gore bir tasarim yapabilir misin?

**Comment by ghost** [comment]
https://github.com/zetaops/ulakbus-ui/commit/70bf9c5828de84870c98de9ba9dbbd7579d95cea ile yapildi

**Comment by ghost** [comment]
arama fonksiyonu duzenlendi ve secilen kullanici saklanarak islem yapilacak sekle getirildi
