### ISSUE TITLE
kullanici ekleme ekrarninda super user zorunlu alan

### ISSUE THREAD

**Issue by alirizakeles** [zetaops/ulakbus-ui#2]
kullanici kayit etme sirasinda super user alani zorunlu gorunuyor. 

super olmayan user eklemek nasil olacak?

super user eklemek istersek de super user eklenmiyor. 

ekran goruntusu:
<img width="694" alt="screen shot 2015-09-17 at 16 39 59" src="https://cloud.githubusercontent.com/assets/671708/9934619/2921413e-5d5b-11e5-9ab9-abd685a90bf9.png">

**Comment by ghost** [comment]
sadece super user konusu degil. ulakbus modellerde duzenlenerek boolean field'lardan required ozellikleri kaldirilarak tum boolean field'lar icin cozulmus olacak.
