### ISSUE TITLE
Hata karşısında daha düzgün davranış

### ISSUE THREAD

**Issue by evrenesat** [zetaops/ulakbus-ui#29]
Mesela aşağıdaki hata döndüğünde,  sessizce dashboarda dönmek yerine bilgilendirici bir hata mesajı faydalı olabilir. info, error, warning simgeli mesaj kutularını daha önce konuşmuştuk.
403 Forbidden
{
    "title": "Permission denied",
    "description": "You don't have required permission: crud.init"
}

**Comment by ghost** [comment]
erkan tasarimlarini gonderdi, ekleniyor

**Comment by ghost** [comment]
#39 ile devam edilecek

**Comment by evrenesat** [comment]
#39'da referans verdiğin 16f86cd ile msjbox işlevi geldi ancak bu issue'nun asıl konusu olan hataları ekrana yansıtma arada kaynamış gibi görünüyor.

**Comment by ghost** [comment]
<img width="1425" alt="screen shot 2015-11-17 at 16 23 07" src="https://cloud.githubusercontent.com/assets/765734/11213975/91389a30-8d47-11e5-8770-86bb89c0f660.png">

@evrenesat yeterli mi?
