### ISSUE TITLE
Ekranda helptext varsa, Formun helptexti basılmıyor.

### ISSUE THREAD

**Issue by evrenesat** [zetaops/ulakbus-ui#35]
Yeni personel akışının hata gözden geçirme ekranında mevcut helptext ekrandayken, iptal seçildiğinde, İptal formunun helptexti yoksayılıyor.

Bu hata ile ortaya çıkan hatalı davranış;  Yeni bir form ekrana basılmadan önce, önceki form ekrandan tamamen temizlenmeli.

**Comment by ghost** [comment]
help text'in abuse edilmeden uyari mesajlarinin goruntulenmesi icin msgbox directive'i yaratildi. #39 ile devam edilecek
