### ISSUE TITLE
Zaten dolmus alanlar icin zorunlu uyarisi

### ISSUE THREAD

**Issue by alirizakeles** [zetaops/ulakbus-ui#36]
Formlarda bazi alanlar dolu olmasina ragmen zorunlu uyarisi veriyor. Ornegin ucretsiz izin eklerken baslangic tarihi secili olmasina ragmen zorunlu alan uyarisi veriyor. 

Ekran goruntusu:
<img width="484" alt="screen shot 2015-11-10 at 07 52 11" src="https://cloud.githubusercontent.com/assets/671708/11055497/6f86c212-8780-11e5-8887-4bc372b8d4e9.png">

**Comment by ghost** [comment]
yeniden uretilemedi
