### ISSUE TITLE
loading gif en solda ustte yer aliyor ve islem yapildigi anlasilamiyor her zaman. 

### ISSUE THREAD

**Issue by kunthar** [zetaops/ulakbus-ui#4]
Islemin surmekte oldugunu kullanici anlamali. Bu bakimdan Kaydet butonunun oldugu bolgede ve biraz daha buyuk olarak yer alabilir mi?

Ornekler:
https://www.brown.edu/sites/default/themes/pawtuxet/img/loader-larger.gif
https://www.brown.edu/sites/default/themes/pawtuxet/img/loader.gif

Burasi da eglenceli. Dunyalar donebilir misal.
http://preloaders.net/en/astronomy

**Comment by ghost** [comment]
tasarima uygun bir loader ile guncellendi
