### ISSUE TITLE
UI ögeleri için API belgelendirmesi

### ISSUE THREAD

**Issue by evrenesat** [zetaops/ulakbus-ui#42]
Aşağıdaki gibi kullanıcı arayüzü ögelerinin nasıl bir API ile çalıştığının belgelendirilmesi faydalı olacaktır. Her ne kadar burada belgelendirlecek olan API, backend API'si bir çok yerde örtüşecek olsa bile, tekrar kullanılabilir UI ögelerinin arkauçtan bağımsız olarak belgelendirilmeleri, projeye sonradan/dışarıdan eklenecek geliştiricilerin işini kolaylaştıracaktır. 
- Listeleme
- Ekleme, 
- Düzenleme, 
- Silme
- Aralık (range) sorgular
- Arama kutusu
- Mesaj kutuları
- Metin kutuları
- Rapor ekranları

**Comment by kunthar** [comment]
- Veritabanı bağlantısını anlatmak.
- Init zamanını sıralı olarak anlatmak
