### ISSUE TITLE
yeni personel ekle, işlem başarısız ekranında düğmelerin biri görünmüyor

### ISSUE THREAD

**Issue by evrenesat** [zetaops/ulakbus-ui#43]
<img width="776" alt="screenshot 2015-11-13 00 38 01" src="https://cloud.githubusercontent.com/assets/591691/11133544/05a4cd0a-899f-11e5-8202-30eed9655bb5.png">

**Comment by evrenesat** [comment]
malesef şuan için bu hata ekranı rasgele olarak %40 olasılıkla ortaya çıkacak şekilde ayarlı :smiling_imp:

**Comment by alirizakeles** [comment]
Form yapisi cok degisti. Yeni durumda tekrar edilmedi.
