### ISSUE TITLE
ssl baglantida api backend in http ile cagrilmasi problemi

### ISSUE THREAD

**Issue by alirizakeles** [zetaops/ulakbus-ui#46]
SSL baglantisinda api backend'in http ile cagrilmasi tarayicinin guvenlik uyarilari vermesine sebep oluyor.

https://www.ulakbus.net/

<img width="788" alt="screen shot 2015-11-18 at 09 28 42" src="https://cloud.githubusercontent.com/assets/671708/11235093/0ec216fe-8dd7-11e5-8ad7-5798977d59ca.png">

**Comment by ghost** [comment]
@alirizakeles ERR_INSECURE_RESPONSE donuyor nightly backendinden

**Comment by ghost** [comment]
backendurl '//example.com' seklinde degistirilerek cozuldu
