### ISSUE TITLE
butonların tamamı Türkçe olmalı

### ISSUE THREAD

**Issue by kunthar** [zetaops/ulakbus-ui#54]
Aynı ekranda Add, Ara ve filtrele butonları yer alıyor. 
Tüm butonların İngilizce OLMAMASI için kontrol edilmesi gerekiyor.

**Comment by kunthar** [comment]
Butonlarin tamami Turkce degil. Butonlarin tamami Turkce olunca bu issue kapatilacaktir.

**Comment by ghost** [comment]
buton isim degerleri backend tarafindan belirleniyor, bu degerler turkcelestirildi ve hardcoded butonlarin da degerleri turkcelestirildi
