### ISSUE TITLE
Modal Seçim Kutusunda Hata

### ISSUE THREAD

**Issue by mithathan** [zetaops/ulakbus-ui#55]
Resimdeki modal seçim kutusundaki Ok tuşu çalışmıyor.
![modal_hata](https://cloud.githubusercontent.com/assets/7900133/11572792/b4a7504e-9a0b-11e5-8f45-ff1efdb2517b.png)

**Comment by ghost** [comment]
@mithathan hangi workflowun ekrani bu mithat?

**Comment by mithathan** [comment]
@evrenkutar ders_ekle.bpmn

**Comment by mithathan** [comment]
http://dev.zetaops.io/#/ders_ekle/do/form?id=

**Comment by ghost** [comment]
@evrenesat bu ekranda da filter_interface widget kullanilmasi uygun mudur?
