### ISSUE TITLE
Form Gruplama

### ISSUE THREAD

**Issue by alirizakeles** [zetaops/ulakbus-ui#7]
Uzun formlarin daha kullanici dostu bir gorunume kavusturulmasi gerekiyor.

Formlar, parcali, acilir kapanir veya step step sekilde gosterilebilir hale getirilmeli.

**Comment by ghost** [comment]
model meta datasinda

form_grouping = [
            {
                "group_title": "Gorev",
                "items": ["gorev_tipi", "kurum_ici_gorev_baslama_tarihi", "kurum_ici_gorev_bitis_tarihi", "birim",
                          "aciklama"],
                "layout": "4",
                "collapse": False
            },
            {
                "group_title": "Resmi Yazi",
                "items": ["resmi_yazi_sayi", "resmi_yazi_tarih"],
                "layout": "2",
                "collapse": False
            }
        ]

seklinde belirlendi. bu donen meta dataya gore form gruplama isine baslandi

**Comment by alirizakeles** [comment]
Done.
